Encoding.default_external = "UTF-8"
source 'https://supermarket.chef.io'

metadata

cookbook 'conda', github: "bdataconsultant/conda-chef", branch: "2.3"
cookbook 'kagent', github: "bdataconsultant/kagent-chef", branch: "2.3"
cookbook 'hops', github: "bdataconsultant/hops-hadoop-chef", branch: "2.3"
cookbook 'ndb', github: "bdataconsultant/ndb-chef", branch: "2.3"
cookbook 'hadoop_spark', github: "bdataconsultant/spark-chef", branch: "2.3"
cookbook 'flink', github: "bdataconsultant/flink-chef", branch: "2.3"
cookbook 'livy', github: "bdataconsultant/livy-chef", branch: "2.3"
cookbook 'epipe', github: "bdataconsultant/epipe-chef", branch: "2.3"
cookbook 'tensorflow', github: "bdataconsultant/tensorflow-chef", branch: "2.3"
cookbook 'dela', github: "bdataconsultant/dela-chef", branch: "2.3"
cookbook 'kzookeeper', github: "bdataconsultant/kzookeeper", branch: "2.3"
cookbook 'kkafka', github: "bdataconsultant/kafka-cookbook", branch: "2.3"
cookbook 'elastic', github: "bdataconsultant/elasticsearch-chef", branch: "2.3"
cookbook 'hopslog', github: "bdataconsultant/hopslog-chef", branch: "2.3"
cookbook 'hopsmonitor', github: "bdataconsultant/hopsmonitor-chef", branch: "2.3"
cookbook 'hops_airflow', github: "bdataconsultant/airflow-chef", branch: "2.3"
cookbook 'hive2', github: "bdataconsultant/hive-chef", branch: "2.3"
cookbook 'consul', github: "bdataconsultant/consul-chef", branch: "2.3"
cookbook 'kube-hops', github: "bdataconsultant/kube-hops-chef", branch: "2.3"
cookbook 'cloud', github: "bdataconsultant/cloud-chef", branch: "2.3"
cookbook 'onlinefs', github: "bdataconsultant/onlinefs-chef", branch: "2.3"

cookbook 'ulimit', github: "bdataconsultant/chef-ulimit", branch: "2.3"
cookbook 'glassfish', github: "bdataconsultant/chef-glassfish", branch: "2.3"
cookbook 'java', github: "bdataconsultant/java", branch: "v7.0.0-1"
